package com.tdu.model;

import com.tdu.model.base.BaseUsr;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Usr extends BaseUsr<Usr> {
	public static final Usr dao = new Usr().dao();
}
